name: Test, Package, and Upload VS Code Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  buildTestDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm test

      - name: Package extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsix-package
          path: '*.vsix'